// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from atwork_interfaces:srv/TaskOpt.idl
// generated code does not contain a copyright notice

#ifndef ATWORK_INTERFACES__SRV__DETAIL__TASK_OPT__STRUCT_H_
#define ATWORK_INTERFACES__SRV__DETAIL__TASK_OPT__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'atwork_task'
#include "atwork_interfaces/msg/detail/task__struct.h"

/// Struct defined in srv/TaskOpt in the package atwork_interfaces.
typedef struct atwork_interfaces__srv__TaskOpt_Request
{
  /// provided task message generated by the atwork_commander, giving current world state, and desired world state
  atwork_interfaces__msg__Task atwork_task;
} atwork_interfaces__srv__TaskOpt_Request;

// Struct for a sequence of atwork_interfaces__srv__TaskOpt_Request.
typedef struct atwork_interfaces__srv__TaskOpt_Request__Sequence
{
  atwork_interfaces__srv__TaskOpt_Request * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} atwork_interfaces__srv__TaskOpt_Request__Sequence;


// Constants defined in the message

// Include directives for member types
// Member 'masterlist'
#include "rosidl_runtime_c/string.h"

/// Struct defined in srv/TaskOpt in the package atwork_interfaces.
typedef struct atwork_interfaces__srv__TaskOpt_Response
{
  /// an optimized task list of instructions
  rosidl_runtime_c__String__Sequence masterlist;
} atwork_interfaces__srv__TaskOpt_Response;

// Struct for a sequence of atwork_interfaces__srv__TaskOpt_Response.
typedef struct atwork_interfaces__srv__TaskOpt_Response__Sequence
{
  atwork_interfaces__srv__TaskOpt_Response * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} atwork_interfaces__srv__TaskOpt_Response__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // ATWORK_INTERFACES__SRV__DETAIL__TASK_OPT__STRUCT_H_
