# service format between navigation and brain nodes
geometry_msgs/PoseStamped goal_point  # goal point to move to
---
uint32 success  # 1 indicates task is complete, 0 means task failed
string instruction # a requested instruction to be done before the next task in the master task list (e.g. to move left/right a little bit)